name: Generate Snake Animation üêç

on:
  schedule:
    - cron: "0 0 * * *"  # –µ–∂–µ–¥–Ω–µ–≤–Ω–æ –≤ –ø–æ–ª–Ω–æ—á—å
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create output directory
        run: mkdir -p dist

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Shoxruh-Baxtiyorov
          output: dist/github-snake.svg
          dark_output: dist/github-snake-dark.svg
          palette: github-dark
          include_private: "false"
          ignore_forks: "true"
          ignore_organizations: "true"

      - name: Push Snake to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
